### ISSUE TITLE
the role does not support multiple mkconf_lines

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-dpb#7]
##### ISSUE TYPE

 - Bug Report

##### ROLE VERSION

```
unreleased
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY

`mkconf_lines` in `proot.conf` can be specified multiple times. `mkconf_lines` does not support line feed, such as `\n`. it is impossible to add multiple lines of `make.conf` content with the role.

##### STEPS TO REPRODUCE

n/a

##### EXPECTED RESULTS

`proot.conf.j2` should support `mkconf_lines` as a list.

```yaml
dpb_proot_config:
  mkconf_lines:
    - FETCH_CMD = /usr/bin/ftp -E
    - FETCH_CMD = /usr/bin/ftp -E
```

should produce:

```
# etc/mk.conf in the build root
FETCH_CMD = /usr/bin/ftp -E
FETCH_CMD = /usr/bin/ftp -E
```

##### ACTUAL RESULTS

it does not.
